; Test file for pep8exec
; Contains all non-NOP-or-RETTR commands, to ensure they work as intended

	STRO	aSTRO,d
	STRO	aSTOP,d
	STRO	aCHARO,d
	CHARO	'\n',i
	STOP

aSTOP:	.ASCII "STOP  \x00"
aSTRO:	.ASCII "STRO  \x00"
aCHARO:	.ASCII "CHARO \x00"

	.END

; MOVSPA MOVFLGA BR BRLE BRLT BREQ BRNE BRGE BRGT BRV BRC CALL
; NOTr NEGr ASLr ASRr ROLr RORr DECI DECO CHARI RETn ADDSP SUBSP
; ADDr SUBr ANDr ORr CPr LDr LDBYTEr STr STBYTEr
